Update update_changelog.yml

diff --git a/.github/workflows/update_changelog.yml b/.github/workflows/update_changelog.yml
--- a/.github/workflows/update_changelog.yml
+++ b/.github/workflows/update_changelog.yml
@@ -21,19 +21,19 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install requests
+          pip install requests pypandoc
 
-      - name: Generate Changelog
+      - name: Generate RTF Changelog
         id: changelog
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          python scripts/update_changelog.py > CHANGELOG.md || exit 1 # Exit if script fails due to rate limit
+          python scripts/update_changelog.py > CHANGELOG.rtf || exit 1 # Exit if script fails due to rate limit
 
-      - name: Commit Changelog
+      - name: Commit RTF Changelog
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git add CHANGELOG.md
+          git add CHANGELOG.rtf
           git commit -m "Update changelog"
           git push
