Update update_changelog.yml

diff --git a/.github/workflows/update_changelog.yml b/.github/workflows/update_changelog.yml
--- a/.github/workflows/update_changelog.yml
+++ b/.github/workflows/update_changelog.yml
@@ -21,24 +21,19 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install requests pypandoc
-          sudo apt-get install -y pandoc
+          pip install requests
 
       - name: Generate Changelog
         id: changelog
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          python scripts/update_changelog.py > CHANGELOG.md || exit 1 # Exit if script fails due to rate limit
+          python scripts/update_changelog.py || exit 1 # Exit if script fails due to rate limit
 
-      - name: Convert Markdown to RTF
-        run: |
-          python scripts/convert_md_to_rtf.py CHANGELOG.md CHANGELOG.rtf
-
-      - name: Commit RTF Changelog
+      - name: Commit Changelog
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git add CHANGELOG.rtf
+          git add CHANGELOG.md CHANGELOG.txt
           git commit -m "Update changelog"
           git push
