Update update_changelog.yml

diff --git a/.github/workflows/update_changelog.yml b/.github/workflows/update_changelog.yml
--- a/.github/workflows/update_changelog.yml
+++ b/.github/workflows/update_changelog.yml
@@ -1,6 +1,9 @@
 name: Update Changelog
 
 on:
+  push:
+    branches:
+      - changelog
   release:
     types: [published]
   workflow_dispatch:
@@ -12,6 +15,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          ref: changelog
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -28,12 +33,12 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          python scripts/create_changelog.py > CHANGELOG.md
+          python scripts/update_changelog.py || exit 1 # Exit if script fails due to rate limit
 
       - name: Commit Changelog
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git add CHANGELOG.md
+          git add changelog.json
           git commit -m "Update changelog"
-          git push
+          git push origin changelog
